### ISSUE TITLE
Can't load app into Ledger Blue

### ISSUE THREAD

**Issue by arigatodl** [LedgerHQ/blue-secure-sdk#2]
I am developing a blue-app and when I run `make load` it gives me following error message.
`Exception : Invalid status 6484 (Are you using the correct targetId?)`

Target id: `--targetId 0x31000004`
`$BOLOS_SDK` is set to `blue-secure-sdk`

I have tried using both the latest version of [`blue-secure-sdk`](https://github.com/LedgerHQ/blue-secure-sdk/tree/3c710b4c62ad847599a2deb0932a50dd1ae4bdff) and 
`blue-load-python`:
```
$ pip show ledgerblue
Name: ledgerblue
Version: 0.1.19
Summary: Python library to communicate with Ledger Blue/Nano S
```

Also my device's version is `MCU: 3.4-hw15` and `SECURE ELEMENT: 2.1.1`

Edit: I have also tried changing `targetId` to `31010004` and it gives me same error message.

**Update:** This issue has been solved by using `0x31010004` as a `targetId` and you can use below python script to get your device's `targetId`.

**Comment by roosmaa** [comment]
I had the same situation, as a quickfix I had to modify the `blue-secure-sdk/include/bolos_target.h` to have the _TARGET_ID_ of `0x31010004`.

Here's a transcript from the Ledger Slack between me and Ledger peeps regarding finding that out:

> roosmaa [10:34 PM]
> @btchip just tried to load an app on my new Blue with the new SDK, getting invalid target id error? The target id passed to the python tool is 0x31000004. Maybe the target ID differs between Blues from before and Blues from the latest batch that recently became available?
> 
> btchip [10:35 PM]
> is it the latest firmware ?
> looks like there's a 1 missing somewhere here
> 
> roosmaa [10:35 PM]
> yup, ledger live doesn't have anything more recent
> 
> btchip [10:35 PM]
> and Manager ?
> 
> roosmaa [10:36 PM]
> didn't try that, 1 sec
> yup, latest firmware according to that as well
> 
> btchip [10:37 PM]
> ok no idea then
> 
> roosmaa [10:38 PM]
> any way to query the device for it's preferred targetId? (because live and manager seem to be able to communicate with it)
> 
> roosmaa [11:10 PM]
> is there some sort of secret "development mode" on the device somewhere that needs to be enabled perhaps?
> 
> btchip [11:10 PM]
> nope
> @oto-ledger will have to chime in on this
> 
> oto-ledger [11:12 PM]
> hi. the targetid is replied when requesting the version using e001000000. the first 4 bytes of the reply is the targetid big endian encoded.
> there are 2 blues the targetid differenciate the hw revision
> 31000004 and 31010004
> i hope it's useful
> 
> roosmaa [11:15 PM]
> Thanks @oto-ledger, looks like my targetId is indeed 0x31010004
> 
> oto-ledger [11:16 PM]
> ok so you have the latest hw15 base
> 
> roosmaa [11:16 PM]
> but this means the blue-secure-sdk is kind of broken by default for people with this hw
> (because the other targetId is hardcoded to the include/bolos_target.h) (edited)
> 
> oto-ledger [11:17 PM]
> sounds like 2 sdk shall be published. i'm a bit late on sdk releasing for the blue. had to focus and debug other higher priorities.
> anyway sdk shall indeed be made available by targetid indeed

**Comment by roosmaa** [comment]
Ok, now saw your edit and that you already tried the `0x31010004` targetId without success. I'll post my debug attempt steps here, maybe they'll be useful.

Passing the `--apdu` flag to ledgerblue to see the raw messages (HID prefixed lines) and where it hangs up. For me it hung up on the very first handshake, like so:

```
$ python -m ledgerblue.listApps --apdu --targetId 0x31000004
Generated random root public key : b'04a6f7447c772f9011bab8fc3c495b43a8a149cac60c911281ff1b043f14c7d76bf53fd1b1adfdc8e5cf50b75a14370c22b6e0303cc0cf0515f565cabdb969b099'
HID => e00400000431000004
HID <= 6484
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mart/Code/Bolos/lib64/python3.6/site-packages/ledgerblue/listApps.py", line 56, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/home/mart/Code/Bolos/lib64/python3.6/site-packages/ledgerblue/deployed.py", line 91, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/home/mart/Code/Bolos/lib64/python3.6/site-packages/ledgerblue/comm.py", line 133, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6484 (Are you using the correct targetId?)
```

Running the get device info that Oto mentioned in the transcript in my previous post to get the actual targetID for the device:

```
$ python
>>> from ledgerblue.comm import getDongle 
>>> dongle = getDongle(True)
>>> a = dongle.exchange(bytearray([0xe0, 0x01, 0x00, 0x00, 0x00]))
>>> print('targetID: 0x{}'.format(a[:4].hex()))
targetID: 0x31010004
```

Hope this helps you debugging this as well.

**Comment by arigatodl** [comment]
@roosmaa Didn't know we could get `targetID` like this. Thanks for the detailed help and will try it. If it works I will close this issue.

**Comment by arigatodl** [comment]
It still gives me the same error.

```python
import binascii
from ledgerblue.comm import getDongle
dongle = getDongle(True)
a = dongle.exchange(bytearray([0xe0, 0x01, 0x00, 0x00, 0x00]))
print('targetID: 0x' + binascii.hexlify(bytes(a[:4])).decode('ascii'))
```
returns `targetID: 0x31010004`

and when I use this target id to load [`blue-app-eth`](https://github.com/LedgerHQ/blue-app-eth) to my device
```
$ make -f Makefile.genericwallet CHAIN=ethereum load
TARGET_NAME=TARGET_BLUE TARGET_ID=31010004
BOLOS_ENV=/home/vagrant/bolos-devenv
BOLOS_ENV=/home/vagrant/bolos-devenv
python -m ledgerblue.loadApp --curve secp256k1 --tlv --targetId 31010004 --delete --fileName bin/app.hex --appName "Ethereum" --appVersion 1.1.2 --dataSize `cat debug/app.map |grep _nvram_data_size | tr -s ' ' | cut -f2 -d' '` `ICONHEX=\`python /home/vagrant/bolos-devenv/blue-secure-sdk-blue-r23/icon.py blue_app_ethereum.gif hexbitmaponly 2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"`   --path "44'" --appFlags 0x840 --path "44'/1'"
Generated random root public key : b'04c59a4431da3d51e3099662e5673f7864967dc3ca466f153ce9691ce37b6ee1202b37f90504fbb5fd989be8641cbcc75bae1af2aab090435c4599fb62c7f33e92'
```

it gives me following message (full)

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/ledger/lib/python3.4/site-packages/ledgerblue/loadApp.py", line 175, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/home/vagrant/ledger/lib/python3.4/site-packages/ledgerblue/deployed.py", line 91, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/home/vagrant/ledger/lib/python3.4/site-packages/ledgerblue/comm.py", line 133, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6484 (Are you using the correct targetId?)
make: *** [load] Error 1
```

I am completely lost here. If it helps I am using python 3.4.

**Comment by arigatodl** [comment]
Oh it was my mistake. I have removed `0x` from the target id while debugging. After adding it and using `0x31010004`.  It has worked. Thanks and I am closing this issue.

**Comment by samngmco** [comment]
I suspect this is related to the firmware version. I had the same problem, I did two things and then it works
1. downgrade my Ubuntu from 20.04 to 18.04 (I am using ledger-app-builder anyway), but I don't think this is related
2. update my ledger firmware (haven't update it in the past 2 years) to 1.6.0, which is then consistent with my ledger-app-builder
